### PR TITLE
Start fixing some of the issues

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by lpw25** [comment]
You need to use:

```
reset_names ();
reset_aliased ();
List.iter mark_type ext.ext_args;
opt_iter mark_type ext.ext_ret_type;
```

before you call `read_extension_constructor` to ensure that type variables and aliases are handled correctly.

**Comment by dsheets** [comment]
What is a block text element (#32)?

Extension constructors don't carry paths and `OpamDocTypes.exn_` has a field `name : string`.

**Comment by dsheets** [comment]
Also, can exceptions have return types or only extension constructors for extensible GADTs? I need to have `exception` and `type 'a foo +=` constructs distinguished.

**Comment by lpw25** [comment]
Exceptions can now (4.02) have return types and they should be displayed with the syntax:

```
exception Foo : int * float -> exn
```

**Pull request merged**
